# Generated by Django 5.0.6 on 2024-06-29 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_image_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ob_no', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('parts', models.CharField(blank=True, max_length=100, null=True)),
                ('operation', models.CharField(blank=True, max_length=1500, null=True)),
                ('type_of_machine', models.CharField(blank=True, max_length=1500, null=True)),
                ('attachments', models.CharField(blank=True, max_length=1500, null=True)),
                ('sam', models.FloatField(blank=True, null=True)),
                ('theoretical_manpower', models.FloatField(blank=True, null=True)),
                ('planned_work_station', models.IntegerField(blank=True, null=True)),
                ('target_100_pcs', models.IntegerField(blank=True, null=True)),
                ('target_60_pcs', models.IntegerField(blank=True, null=True)),
                ('seam_length', models.IntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=1500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ob_detail',
            },
        ),
    ]
